// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCoupT0hC8f-9szs6ydleSzytZIrcYqw',
    appId: '1:153114493840:web:6d68fe053709edc901e915',
    messagingSenderId: '153114493840',
    projectId: 'demoprojectdm',
    authDomain: 'demoprojectdm.firebaseapp.com',
    storageBucket: 'demoprojectdm.firebasestorage.app',
    measurementId: 'G-HHK4Z7Q9D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfxWVZZmr9b8zjlL53Rhc5WnU5dGAyaBo',
    appId: '1:153114493840:android:a006ed80c2e00eae01e915',
    messagingSenderId: '153114493840',
    projectId: 'demoprojectdm',
    storageBucket: 'demoprojectdm.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJCoupT0hC8f-9szs6ydleSzytZIrcYqw',
    appId: '1:153114493840:web:82410eeb3bab671c01e915',
    messagingSenderId: '153114493840',
    projectId: 'demoprojectdm',
    authDomain: 'demoprojectdm.firebaseapp.com',
    storageBucket: 'demoprojectdm.firebasestorage.app',
    measurementId: 'G-SQND5Z0CGB',
  );
}
